// ---------------------------------------------------------------------------
// main
#ifndef GAME_STATE_LIST_HPP
#define GAME_STATE_LIST_HPP

enum GameState
{
	GAME_STATE_MENU = 0,
	GAME_STATE_SHOP,
	GAME_STATE_PLAYING,
	GAME_STATE_LEVEL_EDITOR,
	GAME_STATE_CUSTOM_PLAY,
	GAME_STATE_SETTINGS,
	GAME_STATE_GAME_OVER,
	GAME_STATE_VICTORY,
	GAME_STATE_RESTART,
	GAME_STATE_QUIT
};

#endif // !GAME_STATE_LIST_HPP